### ISSUE TITLE
关于数据集能否公开的的问题

### ISSUE THREAD

**Issue by LittleSJL** [bbruceyuan/FiTSA#1]
作者您好，首先非常感谢您的无私奉献，整理了中文金融领域的情感分析数据集，以及测试和整理了众多模型及方法。
由于目前网络上关于情感分析的数据集，多为诸如 微博、购物评论等偏口语化的数据集，书面化的金融、法律类数据几乎找不到。
所以冒昧的请问作者，您的数据集方便公开吗？

**Comment by bbruceyuan** [comment]
您好，您可以发邮件问一下我们导师，因为这是一个和公司合作的项目，xuruifeng@hitsz.edu.cn
