### ISSUE TITLE
请问代码中如何体现target-based？

### ISSUE THREAD

**Issue by christineaa** [bbruceyuan/FiTSA#2]
如题

**Comment by bbruceyuan** [comment]
您是说 我们的代码没有体现 文章标题的 Target-based 吗？

**Comment by christineaa** [comment]
> 您是说 我们的代码没有体现 文章标题的 Target-based 吗？

是的

**Comment by bbruceyuan** [comment]
这个指的是数据集特点，和代码没有关系。在情感分析里面，aspect-based sentiment analysis 和target-based sentiment analysis算是固定用法吧。（因为在文章中，没有报告其他的实验结果。实际上我们做了一个多target卷积，然后与BERT的CLS标签向量拼接，相对于BERT-baseline 有一定的效果提升，但是因为文章主题不是说模型，所以就没有报告）
