### ISSUE TITLE
Dataset for benchmarking

### ISSUE THREAD

**Issue by neoyipeng2018** [bbruceyuan/FiTSA#3]
Hi Bruce,

Thanks for the paper, think its a great contribution to the currently limited Chinese NLP space.

Wondering if the train/val data set will be made public? Would love to test out new models on the benchmarking dataset.

Thanks in advance,
Yi Peng

**Comment by bbruceyuan** [comment]
Hi. I am glad you are interested in this work. While this dataset is sponsored by company. So I can not make it public. 

But you can email my tutor (the corresponding author) and ask for dataset. email address is: xuruifeng@hitsz.edu.cn

**Comment by neoyipeng2018** [comment]
Thanks Chaofa,

I tried emailing your tutor, but the email bounced - can I check if the
address is correct?

**Comment by bbruceyuan** [comment]
or you can use this one.    xuruifeng@hit.edu.cn

**Comment by neoyipeng2018** [comment]
thanks so much! 😀
